/**
 * Routes for DataPlay
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDataPlay, getDataPlay, listDataPlays, updateDataPlay } from "../handlers/data-play.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataPlayRoutes(fastify: FastifyInstance) {
  // POST /v1/data-plays (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/data-plays",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataplayDependenciesForRequest();
        await createDataPlay(request, reply, deps);
      });
    }
  );


  // GET /v1/data-plays (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-plays",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataplayDependenciesForRequest();
        await listDataPlays(request, reply, deps);
      });
    }
  );


  // GET /v1/data-plays/{dataPlayId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-plays/:dataPlayId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dataPlayId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataplayDependenciesForRequest();
        await getDataPlay(request, reply, deps);
      });
    }
  );


  // PATCH /v1/data-plays/{dataPlayId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/data-plays/:dataPlayId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dataPlayId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataplayDependenciesForRequest();
        await updateDataPlay(request, reply, deps);
      });
    }
  );


}
