/**
 * Alliances DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alliances Domain Module - Composition root
 *
 * DDD: Composition root for alliances domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AllianceRepositoryAdapter,
} from "@asiora/adapters/alliances";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAllianceScore,
  ExecuteGetAllianceScore,
  ExecuteListAllianceScores,
} from "@asiora/services/alliances/usecases";
// Ports (interfaces)
import type {
  AllianceRepository,
} from "@asiora/services/alliances/ports";

export interface AlliancesDomainModule {
  repos: {
    alliances: AllianceRepository;
  };
  useCases: {
    alliances: {
      create: ExecuteCreateAllianceScore;
      get: ExecuteGetAllianceScore;
      list: ExecuteListAllianceScores;
    };
  };
}

export function buildAlliancesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AlliancesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      alliances?: AllianceRepository;
    } = {};

    obj.alliances = new AllianceRepositoryAdapter(dynamoClient);
    return {
      alliances: obj.alliances!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    alliances: {
      create: new ExecuteCreateAllianceScore(executionContext, idGenerator, repos.alliances),
      get: new ExecuteGetAllianceScore(executionContext, idGenerator, repos.alliances),
      list: new ExecuteListAllianceScores(executionContext, idGenerator, repos.alliances),
    },
  };
  return { repos, useCases: useCases as AlliancesDomainModule["useCases"] };
}
