/**
 * GetIdeaIntake handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getIdeaIntake } from "@asiora/api-server/domains/intakes/handlers";
import type { IntakesDDDDependencies } from "@asiora/api-server/domains/intakes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { INTAKES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetIdeaIntake", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IntakesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IntakesDDDDependencies>(
      INTAKES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetIdeaIntake, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { intakeId: entity.id };

    await getIdeaIntake(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetIdeaIntake.execute).toHaveBeenCalledWith(expect.objectContaining({ intakeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { intakeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetIdeaIntake, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getIdeaIntake(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
