/**
 * Handlers for Scenario
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScenariosDomainModule } from "../dependencies/scenarios-ddd.dependencies.js";
import type { GetInitiativeScenarioInput, ListScenarioPosturesInput, SetInsuranceScenarioInput } from "@asiora/services/scenarios";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/scenarios
 * Operation: listScenarioPostures
 */
export async function listScenarioPostures(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], unposturedOnly?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ScenariosDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListScenarioPosturesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.scenarios.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/initiatives/{initiativeId}/scenario
 * Operation: getInitiativeScenario
 */
export async function getInitiativeScenario(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScenariosDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetInitiativeScenarioInput = {
    initiativeId: request.params.initiativeId,
  };
  const result = await deps.useCases.scenarios.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/initiatives/{initiativeId}/scenario
 * Operation: setInsuranceScenario
 */
export async function setInsuranceScenario(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScenariosDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SetInsuranceScenarioInput = {
    initiativeId: request.params.initiativeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.scenarios.update.execute(input);
  return reply.code(200).send(result);
}


