/**
 * PackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PackRepository,
} from "@asiora/services/packs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PackRepositoryDdb } from "./pack-repository.ddb.js";

/**
 * PackRepositoryAdapter
 *
 * Implements PackRepository port for infrastructure layer.
 */
export class PackRepositoryAdapter implements PackRepository {
  private readonly ddb: PackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PackRepositoryDdb(this.dynamoClient);
  }

  async listBoardPacks(input: Parameters<PackRepository['listBoardPacks']>[0]): Promise<Awaited<ReturnType<PackRepository['listBoardPacks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBoardPacks(input);
  }

  async createBoardPack(input: Parameters<PackRepository['createBoardPack']>[0]): Promise<Awaited<ReturnType<PackRepository['createBoardPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBoardPack(input);
  }

  async getBoardPack(input: Parameters<PackRepository['getBoardPack']>[0]): Promise<Awaited<ReturnType<PackRepository['getBoardPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBoardPack(input);
  }
}
