/**
 * ListOverlap DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListOverlapClustersParams } from "@asiora/core/overlaps";

export function createListOverlapRequest(overrides: Partial<ListOverlapClustersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
