/**
 * Diligence DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Diligence Domain Module - Composition root
 *
 * DDD: Composition root for diligence domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DiligenceRepositoryAdapter,
} from "@asiora/adapters/diligence";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDiligence,
  ExecuteListDiligenceChecklists,
  ExecuteUpsertDiligence,
} from "@asiora/services/diligence/usecases";
// Ports (interfaces)
import type {
  DiligenceRepository,
} from "@asiora/services/diligence/ports";

export interface DiligenceDomainModule {
  repos: {
    diligences: DiligenceRepository;
  };
  useCases: {
    diligences: {
      get: ExecuteUpsertDiligence;
      list: ExecuteListDiligenceChecklists;
    };
  };
}

export function buildDiligenceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DiligenceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      diligences?: DiligenceRepository;
    } = {};

    obj.diligences = new DiligenceRepositoryAdapter(dynamoClient);
    return {
      diligences: obj.diligences!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    diligences: {
      get: new ExecuteUpsertDiligence(executionContext, idGenerator, repos.diligences),
      list: new ExecuteListDiligenceChecklists(executionContext, idGenerator, repos.diligences),
    },
  };
  return { repos, useCases: useCases as DiligenceDomainModule["useCases"] };
}
