/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Scenarios Domain Use Cases
 * 
 * List of all use case names for the scenarios domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SCENARIOS_USE_CASES = [
  "executeGetInitiativeScenario",
  "executeListScenarioPostures",
  "executeSetInsuranceScenario"
] as const;
