/**
 * Repository interface for DataPlay
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DataPlayEntity
} from "../models/data-play.entity.js";
import type {
  ListDataPlaysParams,
  DataPlay,
  UpdateDataPlayRequestInput
} from "../types/index.js";
/**
 * DataPlayRepository Interface
 */
export interface DataPlayRepository extends CreateUpdateReadRepository<DataPlayEntity, DataPlay, UpdateDataPlayRequestInput, string, ListDataPlaysParams> {

}
