/**
 * ScenarioRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScenarioRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScenarioRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScenarioRepository,
} from "@asiora/services/scenarios";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScenarioRepositoryDdb } from "./scenario-repository.ddb.js";

/**
 * ScenarioRepositoryAdapter
 *
 * Implements ScenarioRepository port for infrastructure layer.
 */
export class ScenarioRepositoryAdapter implements ScenarioRepository {
  private readonly ddb: ScenarioRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScenarioRepositoryDdb(this.dynamoClient);
  }

  async listScenarioPostures(input: Parameters<ScenarioRepository['listScenarioPostures']>[0]): Promise<Awaited<ReturnType<ScenarioRepository['listScenarioPostures']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listScenarioPostures(input);
  }

  async getInitiativeScenario(input: Parameters<ScenarioRepository['getInitiativeScenario']>[0]): Promise<Awaited<ReturnType<ScenarioRepository['getInitiativeScenario']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getInitiativeScenario(input);
  }

  async setInsuranceScenario(input: Parameters<ScenarioRepository['setInsuranceScenario']>[0]): Promise<Awaited<ReturnType<ScenarioRepository['setInsuranceScenario']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setInsuranceScenario(input);
  }
}
