/**
 * ExecuteGetOverlapCluster - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetOverlapCluster Use Case
 *
 * DDD: Application use case for get Overlap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetOverlapClusterInput, GetOverlapClusterOutput } from "../dto/overlap.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { OverlapRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetOverlapCluster {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly overlap: OverlapRepository
  ) {}

  async execute(input: GetOverlapClusterInput): Promise<GetOverlapClusterOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ovlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).overlapId) {
      throw new ValidationError("overlapId is required");
    }
    const overlapId = (input as any).overlapId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.overlap.getOverlapCluster({ overlapId: overlapId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${overlapId}`);
    }

    return entity as GetOverlapClusterOutput;
  }
}
