/**
 * DataPlayRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataPlayRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataPlayRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataPlayRepository,
} from "@asiora/services/dataplay";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataPlayRepositoryDdb } from "./data-play-repository.ddb.js";

/**
 * DataPlayRepositoryAdapter
 *
 * Implements DataPlayRepository port for infrastructure layer.
 */
export class DataPlayRepositoryAdapter implements DataPlayRepository {
  private readonly ddb: DataPlayRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataPlayRepositoryDdb(this.dynamoClient);
  }

  async listDataPlays(input: Parameters<DataPlayRepository['listDataPlays']>[0]): Promise<Awaited<ReturnType<DataPlayRepository['listDataPlays']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataPlays(input);
  }

  async createDataPlay(input: Parameters<DataPlayRepository['createDataPlay']>[0]): Promise<Awaited<ReturnType<DataPlayRepository['createDataPlay']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDataPlay(input);
  }

  async getDataPlay(input: Parameters<DataPlayRepository['getDataPlay']>[0]): Promise<Awaited<ReturnType<DataPlayRepository['getDataPlay']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataPlay(input);
  }

  async updateDataPlay(input: Parameters<DataPlayRepository['updateDataPlay']>[0]): Promise<Awaited<ReturnType<DataPlayRepository['updateDataPlay']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateDataPlay(input);
  }
}
