/**
 * GetDiligence DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDiligenceParams } from "@asiora/core/diligence";

export function createGetDiligenceRequest(overrides: Partial<GetDiligenceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
