/**
 * DiligenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiligenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DiligenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DiligenceRepository,
} from "@asiora/services/diligence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DiligenceRepositoryDdb } from "./diligence-repository.ddb.js";

/**
 * DiligenceRepositoryAdapter
 *
 * Implements DiligenceRepository port for infrastructure layer.
 */
export class DiligenceRepositoryAdapter implements DiligenceRepository {
  private readonly ddb: DiligenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DiligenceRepositoryDdb(this.dynamoClient);
  }

  async listDiligenceChecklists(input: Parameters<DiligenceRepository['listDiligenceChecklists']>[0]): Promise<Awaited<ReturnType<DiligenceRepository['listDiligenceChecklists']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDiligenceChecklists(input);
  }

  async getDiligence(input: Parameters<DiligenceRepository['getDiligence']>[0]): Promise<Awaited<ReturnType<DiligenceRepository['getDiligence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDiligence(input);
  }

  async upsertDiligence(input: Parameters<DiligenceRepository['upsertDiligence']>[0]): Promise<Awaited<ReturnType<DiligenceRepository['upsertDiligence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertDiligence(input);
  }
}
