/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as alliancesRoutes from "../../domains/alliances/routes/index.js";
import * as dataplayRoutes from "../../domains/dataplay/routes/index.js";
import * as decisionsRoutes from "../../domains/decisions/routes/index.js";
import * as diligenceRoutes from "../../domains/diligence/routes/index.js";
import * as gatesRoutes from "../../domains/gates/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as initiativesRoutes from "../../domains/initiatives/routes/index.js";
import * as intakesRoutes from "../../domains/intakes/routes/index.js";
import * as overlapsRoutes from "../../domains/overlaps/routes/index.js";
import * as packsRoutes from "../../domains/packs/routes/index.js";
import * as scenariosRoutes from "../../domains/scenarios/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "alliances", mod: alliancesRoutes },
  { domain: "dataplay", mod: dataplayRoutes },
  { domain: "decisions", mod: decisionsRoutes },
  { domain: "diligence", mod: diligenceRoutes },
  { domain: "gates", mod: gatesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "initiatives", mod: initiativesRoutes },
  { domain: "intakes", mod: intakesRoutes },
  { domain: "overlaps", mod: overlapsRoutes },
  { domain: "packs", mod: packsRoutes },
  { domain: "scenarios", mod: scenariosRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
