/**
 * UpdateInitiative handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateInitiative } from "@asiora/api-server/domains/initiatives/handlers";
import type { InitiativesDDDDependencies } from "@asiora/api-server/domains/initiatives";
import { createInitiative as createInitiativeEntity } from "@asiora/factories/initiatives";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { INITIATIVES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateInitiative", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InitiativesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InitiativesDDDDependencies>(
      INITIATIVES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createInitiativeEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { initiativeId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateInitiative, "execute").mockResolvedValue(useCaseResult);

    await updateInitiative(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateInitiative.execute).toHaveBeenCalledWith(expect.objectContaining({ initiativeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
