/**
 * ExecuteListDiligenceChecklists - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDiligenceChecklists Use Case
 *
 * DDD: Application use case for list Diligence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDiligenceChecklistsInput, ListDiligenceChecklistsOutput } from "../dto/diligence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { DiligenceRepository } from "../ports";

export class ExecuteListDiligenceChecklists {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly diligence: DiligenceRepository
  ) {}

  async execute(input: ListDiligenceChecklistsInput): Promise<ListDiligenceChecklistsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dilId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.diligence.listDiligenceChecklists({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDiligenceChecklistsOutput;
  }
}
