/**
 * Overlap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Overlap DTOs
 *
 * DDD: Application DTOs for Overlap use cases.
 */

import type { CreateOverlapClusterRequestInput, GetOverlapClusterParams, ListOverlapClustersParams } from "@asiora/core/overlaps/types";

export type ListOverlapClustersInput = ListOverlapClustersParams;

export type CreateOverlapClusterInput = CreateOverlapClusterRequestInput;

export type GetOverlapClusterInput = GetOverlapClusterParams;

export type ListOverlapClustersOutput = {};

export type CreateOverlapClusterOutput = {};

export type GetOverlapClusterOutput = {};
