/**
 * Resolve DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Resolve DTOs
 *
 * DDD: Application DTOs for Resolve use cases.
 */

import type { ResolveOverlapClusterParams, ResolveOverlapClusterRequestInput } from "@asiora/core/overlaps/types";

export type ResolveOverlapClusterInput = ResolveOverlapClusterParams & ResolveOverlapClusterRequestInput;

export type ResolveOverlapClusterOutput = {};
