/**
 * AssignRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssignRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssignRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssignRepository,
} from "@asiora/services/intakes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssignRepositoryDdb } from "./assign-repository.ddb.js";

/**
 * AssignRepositoryAdapter
 *
 * Implements AssignRepository port for infrastructure layer.
 */
export class AssignRepositoryAdapter implements AssignRepository {
  private readonly ddb: AssignRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssignRepositoryDdb(this.dynamoClient);
  }

  async assignIdeaIntake(input: Parameters<AssignRepository['assignIdeaIntake']>[0]): Promise<Awaited<ReturnType<AssignRepository['assignIdeaIntake']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.assignIdeaIntake(input);
  }
}
