/**
 * ConvertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConvertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConvertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConvertRepository,
} from "@asiora/services/intakes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConvertRepositoryDdb } from "./convert-repository.ddb.js";

/**
 * ConvertRepositoryAdapter
 *
 * Implements ConvertRepository port for infrastructure layer.
 */
export class ConvertRepositoryAdapter implements ConvertRepository {
  private readonly ddb: ConvertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConvertRepositoryDdb(this.dynamoClient);
  }

  async convertIdeaIntake(input: Parameters<ConvertRepository['convertIdeaIntake']>[0]): Promise<Awaited<ReturnType<ConvertRepository['convertIdeaIntake']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.convertIdeaIntake(input);
  }
}
