/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./assign-repository.ddb.js";
export * from "./convert-repository.ddb.js";
export * from "./expire-repository.ddb.js";
export * from "./intake-repository.ddb.js";
export * from "./assign-repository.adapter.js";
export * from "./convert-repository.adapter.js";
export * from "./expire-repository.adapter.js";
export * from "./intake-repository.adapter.js";
