/**
 * IntakeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntakeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IntakeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IntakeRepository,
} from "@asiora/services/intakes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IntakeRepositoryDdb } from "./intake-repository.ddb.js";

/**
 * IntakeRepositoryAdapter
 *
 * Implements IntakeRepository port for infrastructure layer.
 */
export class IntakeRepositoryAdapter implements IntakeRepository {
  private readonly ddb: IntakeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IntakeRepositoryDdb(this.dynamoClient);
  }

  async listIdeaIntakes(input: Parameters<IntakeRepository['listIdeaIntakes']>[0]): Promise<Awaited<ReturnType<IntakeRepository['listIdeaIntakes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listIdeaIntakes(input);
  }

  async createIdeaIntake(input: Parameters<IntakeRepository['createIdeaIntake']>[0]): Promise<Awaited<ReturnType<IntakeRepository['createIdeaIntake']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createIdeaIntake(input);
  }

  async getIdeaIntake(input: Parameters<IntakeRepository['getIdeaIntake']>[0]): Promise<Awaited<ReturnType<IntakeRepository['getIdeaIntake']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getIdeaIntake(input);
  }
}
