/**
 * ExecuteConvertIdeaIntake - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteConvertIdeaIntake Use Case
 *
 * DDD: Application use case for get Convert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ConvertIdeaIntakeInput, ConvertIdeaIntakeOutput } from "../dto/convert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { ConvertRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteConvertIdeaIntake {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly convert: ConvertRepository
  ) {}

  async execute(input: ConvertIdeaIntakeInput): Promise<ConvertIdeaIntakeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.intId();

    // All field names extracted from OpenAPI spec: name, owner, vertical
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).intakeId) {
      throw new ValidationError("intakeId is required");
    }
    const intakeId = (input as any).intakeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.convert.convertIdeaIntake({ ...input, intakeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${intakeId}`);
    }

    return entity as ConvertIdeaIntakeOutput;
  }
}
