/**
 * ExecuteCreateIdeaIntake - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateIdeaIntake Use Case
 *
 * DDD: Application use case for create Intake.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateIdeaIntakeInput, CreateIdeaIntakeOutput } from "../dto/intake.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { IntakeRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateIdeaIntake {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly intake: IntakeRepository
  ) {}

  async execute(input: CreateIdeaIntakeInput): Promise<CreateIdeaIntakeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.intId();

    // All field names extracted from OpenAPI spec: notes, source, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.title) {
      throw new ValidationError("title is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (intakes domain)
    const entityId = this.idGenerator.intId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.intake.createIdeaIntake({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateIdeaIntakeOutput;
  }
}
