/**
 * ExecuteListIdeaIntakes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListIdeaIntakes Use Case
 *
 * DDD: Application use case for list Intake.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListIdeaIntakesInput, ListIdeaIntakesOutput } from "../dto/intake.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { IntakeRepository } from "../ports";

export class ExecuteListIdeaIntakes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly intake: IntakeRepository
  ) {}

  async execute(input: ListIdeaIntakesInput): Promise<ListIdeaIntakesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.intId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.intake.listIdeaIntakes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListIdeaIntakesOutput;
  }
}
