/**
 * ExecuteAssignIdeaIntake - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAssignIdeaIntake Use Case
 *
 * DDD: Application use case for get Assign.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AssignIdeaIntakeInput, AssignIdeaIntakeOutput } from "../dto/assign.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { AssignRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAssignIdeaIntake {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly assign: AssignRepository
  ) {}

  async execute(input: AssignIdeaIntakeInput): Promise<AssignIdeaIntakeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.intId();

    // All field names extracted from OpenAPI spec: owner
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).intakeId) {
      throw new ValidationError("intakeId is required");
    }
    const intakeId = (input as any).intakeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.assign.assignIdeaIntake({ ...input, intakeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${intakeId}`);
    }

    return entity as AssignIdeaIntakeOutput;
  }
}
