/**
 * Handlers for DataPlay
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DataplayDomainModule } from "../dependencies/dataplay-ddd.dependencies.js";
import type { CreateDataPlayInput, GetDataPlayInput, ListDataPlaysInput, UpdateDataPlayInput } from "@asiora/services/dataplay";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/data-plays
 * Operation: listDataPlays
 */
export async function listDataPlays(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], initiativeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DataplayDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDataPlaysInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.dataPlays.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/data-plays
 * Operation: createDataPlay
 */
export async function createDataPlay(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DataplayDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDataPlayInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dataPlays.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/data-plays/{dataPlayId}
 * Operation: getDataPlay
 */
export async function getDataPlay(
  request: FastifyRequest<{ Params: { dataPlayId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DataplayDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDataPlayInput = {
    dataPlayId: request.params.dataPlayId,
  };
  const result = await deps.useCases.dataPlays.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/data-plays/{dataPlayId}
 * Operation: updateDataPlay
 */
export async function updateDataPlay(
  request: FastifyRequest<{ Params: { dataPlayId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DataplayDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateDataPlayInput = {
    dataPlayId: request.params.dataPlayId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dataPlays.update.execute(input);
  return reply.code(200).send(result);
}


