/**
 * DataPlay Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/dataplay.openapi.types.js";
import { schemas } from "../schemas/dataplay.schemas.js";

/**
 * Entity: DataPlayEntity
 * Description: Represents the DataPlay domain model.
 * Source: schemas.DataPlay
 * Type: Domain Entity (API)
 */
export const DataPlayEntitySchema = schemas.DataPlay;
export type DataPlayEntity = components["schemas"]["DataPlay"];
