/**
 * ListIntake DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListIdeaIntakesParams } from "@asiora/core/intakes";

export function createListIntakeRequest(overrides: Partial<ListIdeaIntakesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
