/**
 * Assign DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assign DTOs
 *
 * DDD: Application DTOs for Assign use cases.
 */

import type { AssignIdeaIntakeParams, AssignIdeaIntakeRequestInput } from "@asiora/core/intakes/types";

export type AssignIdeaIntakeInput = AssignIdeaIntakeParams & AssignIdeaIntakeRequestInput;

export type AssignIdeaIntakeOutput = {};
