/**
 * Convert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Convert DTOs
 *
 * DDD: Application DTOs for Convert use cases.
 */

import type { ConvertIdeaIntakeParams, ConvertIdeaIntakeRequestInput } from "@asiora/core/intakes/types";

export type ConvertIdeaIntakeInput = ConvertIdeaIntakeParams & ConvertIdeaIntakeRequestInput;

export type ConvertIdeaIntakeOutput = {};
