/**
 * Expire DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Expire DTOs
 *
 * DDD: Application DTOs for Expire use cases.
 */

import type { ExpireIdeaIntakeParams } from "@asiora/core/intakes/types";

export type ExpireIdeaIntakeInput = ExpireIdeaIntakeParams;

export type ExpireIdeaIntakeOutput = {};
