/**
 * Routes for Convert
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { convertIdeaIntake } from "../handlers/convert.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function convertRoutes(fastify: FastifyInstance) {
  // POST /v1/intakes/{intakeId}/convert (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/intakes/:intakeId/convert",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { intakeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIntakesDependenciesForRequest();
        await convertIdeaIntake(request, reply, deps);
      });
    }
  );


}
