/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { assignRoutes } from "./assign.routes.js";
export { convertRoutes } from "./convert.routes.js";
export { expireRoutes } from "./expire.routes.js";
export { intakeRoutes } from "./intake.routes.js";
