/**
 * ExecuteGetInitiativeScenario - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetInitiativeScenario Use Case
 *
 * DDD: Application use case for get Scenario.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetInitiativeScenarioInput, GetInitiativeScenarioOutput } from "../dto/scenario.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { ScenarioRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetInitiativeScenario {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scenario: ScenarioRepository
  ) {}

  async execute(input: GetInitiativeScenarioInput): Promise<GetInitiativeScenarioOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    const initiativeId = (input as any).initiativeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scenario.getInitiativeScenario({ initiativeId: initiativeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${initiativeId}`);
    }

    return entity as GetInitiativeScenarioOutput;
  }
}
