/**
 * ExecuteListScenarioPostures - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListScenarioPostures Use Case
 *
 * DDD: Application use case for list Scenario.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListScenarioPosturesInput, ListScenarioPosturesOutput } from "../dto/scenario.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { ScenarioRepository } from "../ports";

export class ExecuteListScenarioPostures {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scenario: ScenarioRepository
  ) {}

  async execute(input: ListScenarioPosturesInput): Promise<ListScenarioPosturesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.scenario.listScenarioPostures({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListScenarioPosturesOutput;
  }
}
