/**
 * Diligence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Diligence DTOs
 *
 * DDD: Application DTOs for Diligence use cases.
 */

import type { GetDiligenceParams, ListDiligenceChecklistsParams, UpsertDiligenceParams, UpsertDiligenceRequestInput } from "@asiora/core/diligence/types";

export type ListDiligenceChecklistsInput = ListDiligenceChecklistsParams;

export type GetDiligenceInput = GetDiligenceParams;

export type UpsertDiligenceInput = UpsertDiligenceParams & UpsertDiligenceRequestInput;

export type ListDiligenceChecklistsOutput = {};

export type GetDiligenceOutput = {};

export type UpsertDiligenceOutput = {};
