/**
 * Overlaps DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Overlaps Domain Module - Composition root
 *
 * DDD: Composition root for overlaps domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  OverlapRepositoryAdapter,
  ResolveRepositoryAdapter,
} from "@asiora/adapters/overlaps";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateOverlapCluster,
  ExecuteGetOverlapCluster,
  ExecuteListOverlapClusters,
  ExecuteResolveOverlapCluster,
} from "@asiora/services/overlaps/usecases";
// Ports (interfaces)
import type {
  OverlapRepository,
  ResolveRepository,
} from "@asiora/services/overlaps/ports";

export interface OverlapsDomainModule {
  repos: {
    overlaps: OverlapRepository;
    resolves: ResolveRepository;
  };
  useCases: {
    overlaps: {
      create: ExecuteCreateOverlapCluster;
      get: ExecuteGetOverlapCluster;
      list: ExecuteListOverlapClusters;
    };
    resolves: {
      get: ExecuteResolveOverlapCluster;
    };
  };
}

export function buildOverlapsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OverlapsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      overlaps?: OverlapRepository;
      resolves?: ResolveRepository;
    } = {};

    obj.overlaps = new OverlapRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    return {
      overlaps: obj.overlaps!,
      resolves: obj.resolves!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    overlaps: {
      create: new ExecuteCreateOverlapCluster(executionContext, idGenerator, repos.overlaps),
      get: new ExecuteGetOverlapCluster(executionContext, idGenerator, repos.overlaps),
      list: new ExecuteListOverlapClusters(executionContext, idGenerator, repos.overlaps),
    },
    resolves: {
      get: new ExecuteResolveOverlapCluster(executionContext, idGenerator, repos.resolves),
    },
  };
  return { repos, useCases: useCases as OverlapsDomainModule["useCases"] };
}
