/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Overlaps Domain Use Cases
 * 
 * List of all use case names for the overlaps domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const OVERLAPS_USE_CASES = [
  "executeCreateOverlapCluster",
  "executeGetOverlapCluster",
  "executeListOverlapClusters",
  "executeResolveOverlapCluster"
] as const;
