/**
 * ScenarioRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScenarioRepository Port
 *
 * DDD: Application port for scenariorepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetInitiativeScenarioInput, GetInitiativeScenarioOutput, ListScenarioPosturesInput, ListScenarioPosturesOutput, SetInsuranceScenarioInput, SetInsuranceScenarioOutput } from "../dto/scenario.dto";
export interface ScenarioRepository {
  listScenarioPostures(input: ListScenarioPosturesInput): Promise<ListScenarioPosturesOutput>;
  getInitiativeScenario(input: GetInitiativeScenarioInput): Promise<GetInitiativeScenarioOutput>;
  setInsuranceScenario(input: SetInsuranceScenarioInput): Promise<SetInsuranceScenarioOutput>;
}

export type { GetInitiativeScenarioInput, GetInitiativeScenarioOutput, ListScenarioPosturesInput, ListScenarioPosturesOutput, SetInsuranceScenarioInput, SetInsuranceScenarioOutput } from "../dto/scenario.dto";
