/**
 * Dataplay DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dataplay Domain Module - Composition root
 *
 * DDD: Composition root for dataplay domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DataPlayRepositoryAdapter,
} from "@asiora/adapters/dataplay";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDataPlay,
  ExecuteGetDataPlay,
  ExecuteListDataPlays,
  ExecuteUpdateDataPlay,
} from "@asiora/services/dataplay/usecases";
// Ports (interfaces)
import type {
  DataPlayRepository,
} from "@asiora/services/dataplay/ports";

export interface DataplayDomainModule {
  repos: {
    dataPlays: DataPlayRepository;
  };
  useCases: {
    dataPlays: {
      create: ExecuteCreateDataPlay;
      get: ExecuteGetDataPlay;
      list: ExecuteListDataPlays;
      update: ExecuteUpdateDataPlay;
    };
  };
}

export function buildDataplayDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DataplayDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dataPlays?: DataPlayRepository;
    } = {};

    obj.dataPlays = new DataPlayRepositoryAdapter(dynamoClient);
    return {
      dataPlays: obj.dataPlays!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dataPlays: {
      create: new ExecuteCreateDataPlay(executionContext, idGenerator, repos.dataPlays),
      get: new ExecuteGetDataPlay(executionContext, idGenerator, repos.dataPlays),
      list: new ExecuteListDataPlays(executionContext, idGenerator, repos.dataPlays),
      update: new ExecuteUpdateDataPlay(executionContext, idGenerator, repos.dataPlays),
    },
  };
  return { repos, useCases: useCases as DataplayDomainModule["useCases"] };
}
