/**
 * Handlers for Convert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IntakesDomainModule } from "../dependencies/intakes-ddd.dependencies.js";
import type { ConvertIdeaIntakeInput } from "@asiora/services/intakes";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/intakes/{intakeId}/convert
 * Operation: convertIdeaIntake
 */
export async function convertIdeaIntake(
  request: FastifyRequest<{ Params: { intakeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IntakesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ConvertIdeaIntakeInput = {
    intakeId: request.params.intakeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.converts.get.execute(input);
  return reply.code(200).send(result);
}


