/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./assign.handlers.js";
export * from "./convert.handlers.js";
export * from "./expire.handlers.js";
export * from "./intake.handlers.js";
