/**
 * DiligenceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiligenceRepository Port
 *
 * DDD: Application port for diligencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDiligenceInput, GetDiligenceOutput, ListDiligenceChecklistsInput, ListDiligenceChecklistsOutput, UpsertDiligenceInput, UpsertDiligenceOutput } from "../dto/diligence.dto";
export interface DiligenceRepository {
  listDiligenceChecklists(input: ListDiligenceChecklistsInput): Promise<ListDiligenceChecklistsOutput>;
  getDiligence(input: GetDiligenceInput): Promise<GetDiligenceOutput>;
  upsertDiligence(input: UpsertDiligenceInput): Promise<UpsertDiligenceOutput>;
}

export type { GetDiligenceInput, GetDiligenceOutput, ListDiligenceChecklistsInput, ListDiligenceChecklistsOutput, UpsertDiligenceInput, UpsertDiligenceOutput } from "../dto/diligence.dto";
