/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAlliancesDomainModule } from "./alliances/dependencies/alliances-ddd.dependencies.js";
export { buildDataplayDomainModule } from "./dataplay/dependencies/dataplay-ddd.dependencies.js";
export { buildDecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export { buildDiligenceDomainModule } from "./diligence/dependencies/diligence-ddd.dependencies.js";
export { buildGatesDomainModule } from "./gates/dependencies/gates-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInitiativesDomainModule } from "./initiatives/dependencies/initiatives-ddd.dependencies.js";
export { buildIntakesDomainModule } from "./intakes/dependencies/intakes-ddd.dependencies.js";
export { buildOverlapsDomainModule } from "./overlaps/dependencies/overlaps-ddd.dependencies.js";
export { buildPacksDomainModule } from "./packs/dependencies/packs-ddd.dependencies.js";
export { buildScenariosDomainModule } from "./scenarios/dependencies/scenarios-ddd.dependencies.js";

// Export all domain dependency types
export type { AlliancesDomainModule } from "./alliances/dependencies/alliances-ddd.dependencies.js";
export type { DataplayDomainModule } from "./dataplay/dependencies/dataplay-ddd.dependencies.js";
export type { DecisionsDomainModule } from "./decisions/dependencies/decisions-ddd.dependencies.js";
export type { DiligenceDomainModule } from "./diligence/dependencies/diligence-ddd.dependencies.js";
export type { GatesDomainModule } from "./gates/dependencies/gates-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InitiativesDomainModule } from "./initiatives/dependencies/initiatives-ddd.dependencies.js";
export type { IntakesDomainModule } from "./intakes/dependencies/intakes-ddd.dependencies.js";
export type { OverlapsDomainModule } from "./overlaps/dependencies/overlaps-ddd.dependencies.js";
export type { PacksDomainModule } from "./packs/dependencies/packs-ddd.dependencies.js";
export type { ScenariosDomainModule } from "./scenarios/dependencies/scenarios-ddd.dependencies.js";
