/**
 * Handlers for Publish
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PacksDomainModule } from "../dependencies/packs-ddd.dependencies.js";
import type { PublishBoardPackInput } from "@asiora/services/packs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/packs/{packId}/publish
 * Operation: publishBoardPack
 */
export async function publishBoardPack(
  request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishBoardPackInput = {
    packId: request.params.packId,
  };
  const result = await deps.useCases.publishes.get.execute(input);
  return reply.code(200).send(result);
}


