/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Alliances Domain Use Cases
 * 
 * List of all use case names for the alliances domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ALLIANCES_USE_CASES = [
  "executeCreateAllianceScore",
  "executeGetAllianceScore",
  "executeListAllianceScores"
] as const;
