/**
 * UpsertDiligence handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: diligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { upsertDiligence } from "@asiora/api-server/domains/diligence/handlers";
import type { DiligenceDDDDependencies } from "@asiora/api-server/domains/diligence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { DILIGENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("UpsertDiligence", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DiligenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DiligenceDDDDependencies>(
      DILIGENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { initiativeId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpsertDiligence, "execute").mockResolvedValue(useCaseResult);

    await upsertDiligence(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpsertDiligence.execute).toHaveBeenCalledWith(expect.objectContaining({ initiativeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
