/**
 * Intakes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Intakes Domain Module - Composition root
 *
 * DDD: Composition root for intakes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssignRepositoryAdapter,
  ConvertRepositoryAdapter,
  ExpireRepositoryAdapter,
  IntakeRepositoryAdapter,
} from "@asiora/adapters/intakes";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssignIdeaIntake,
  ExecuteConvertIdeaIntake,
  ExecuteCreateIdeaIntake,
  ExecuteExpireIdeaIntake,
  ExecuteGetIdeaIntake,
  ExecuteListIdeaIntakes,
} from "@asiora/services/intakes/usecases";
// Ports (interfaces)
import type {
  AssignRepository,
  ConvertRepository,
  ExpireRepository,
  IntakeRepository,
} from "@asiora/services/intakes/ports";

export interface IntakesDomainModule {
  repos: {
    assigns: AssignRepository;
    converts: ConvertRepository;
    expires: ExpireRepository;
    intakes: IntakeRepository;
  };
  useCases: {
    assigns: {
      get: ExecuteAssignIdeaIntake;
    };
    converts: {
      get: ExecuteConvertIdeaIntake;
    };
    expires: {
      get: ExecuteExpireIdeaIntake;
    };
    intakes: {
      create: ExecuteCreateIdeaIntake;
      get: ExecuteGetIdeaIntake;
      list: ExecuteListIdeaIntakes;
    };
  };
}

export function buildIntakesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): IntakesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assigns?: AssignRepository;
      converts?: ConvertRepository;
      expires?: ExpireRepository;
      intakes?: IntakeRepository;
    } = {};

    obj.assigns = new AssignRepositoryAdapter(dynamoClient);
    obj.converts = new ConvertRepositoryAdapter(dynamoClient);
    obj.expires = new ExpireRepositoryAdapter(dynamoClient);
    obj.intakes = new IntakeRepositoryAdapter(dynamoClient);
    return {
      assigns: obj.assigns!,
      converts: obj.converts!,
      expires: obj.expires!,
      intakes: obj.intakes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assigns: {
      get: new ExecuteAssignIdeaIntake(executionContext, idGenerator, repos.assigns),
    },
    converts: {
      get: new ExecuteConvertIdeaIntake(executionContext, idGenerator, repos.converts),
    },
    expires: {
      get: new ExecuteExpireIdeaIntake(executionContext, idGenerator, repos.expires),
    },
    intakes: {
      create: new ExecuteCreateIdeaIntake(executionContext, idGenerator, repos.intakes),
      get: new ExecuteGetIdeaIntake(executionContext, idGenerator, repos.intakes),
      list: new ExecuteListIdeaIntakes(executionContext, idGenerator, repos.intakes),
    },
  };
  return { repos, useCases: useCases as IntakesDomainModule["useCases"] };
}
