/**
 * Gates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Gates Domain Module - Composition root
 *
 * DDD: Composition root for gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EthicRepositoryAdapter,
  TalentRepositoryAdapter,
  WaiverRepositoryAdapter,
} from "@asiora/adapters/gates";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteEvaluateTalentGate,
  ExecuteListEthicsFlags,
  ExecuteListTalentGates,
  ExecuteRaiseEthicsFlag,
  ExecuteWaiveEthicsFlag,
} from "@asiora/services/gates/usecases";
// Ports (interfaces)
import type {
  EthicRepository,
  TalentRepository,
  WaiverRepository,
} from "@asiora/services/gates/ports";

export interface GatesDomainModule {
  repos: {
    ethics: EthicRepository;
    talents: TalentRepository;
    waivers: WaiverRepository;
  };
  useCases: {
    ethics: {
      get: ExecuteRaiseEthicsFlag;
      list: ExecuteListEthicsFlags;
    };
    talents: {
      create: ExecuteEvaluateTalentGate;
      list: ExecuteListTalentGates;
    };
    waivers: {
      get: ExecuteWaiveEthicsFlag;
    };
  };
}

export function buildGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      ethics?: EthicRepository;
      talents?: TalentRepository;
      waivers?: WaiverRepository;
    } = {};

    obj.ethics = new EthicRepositoryAdapter(dynamoClient);
    obj.talents = new TalentRepositoryAdapter(dynamoClient);
    obj.waivers = new WaiverRepositoryAdapter(dynamoClient);
    return {
      ethics: obj.ethics!,
      talents: obj.talents!,
      waivers: obj.waivers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    ethics: {
      get: new ExecuteRaiseEthicsFlag(executionContext, idGenerator, repos.ethics),
      list: new ExecuteListEthicsFlags(executionContext, idGenerator, repos.ethics),
    },
    talents: {
      create: new ExecuteEvaluateTalentGate(executionContext, idGenerator, repos.talents),
      list: new ExecuteListTalentGates(executionContext, idGenerator, repos.talents),
    },
    waivers: {
      get: new ExecuteWaiveEthicsFlag(executionContext, idGenerator, repos.waivers),
    },
  };
  return { repos, useCases: useCases as GatesDomainModule["useCases"] };
}
