/**
 * ExecuteGetDataPlay - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDataPlay Use Case
 *
 * DDD: Application use case for get DataPlay.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDataPlayInput, GetDataPlayOutput } from "../dto/data-play.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { DataPlayRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDataPlay {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataPlay: DataPlayRepository
  ) {}

  async execute(input: GetDataPlayInput): Promise<GetDataPlayOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dplId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dataPlayId) {
      throw new ValidationError("dataPlayId is required");
    }
    const dataplayId = (input as any).dataPlayId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataPlay.getDataPlay({ dataPlayId: dataplayId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${dataplayId}`);
    }

    return entity as GetDataPlayOutput;
  }
}
