/**
 * ExecuteUpdateDataPlay - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateDataPlay Use Case
 *
 * DDD: Application use case for update DataPlay.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateDataPlayInput, UpdateDataPlayOutput } from "../dto/data-play.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { DataPlayRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateDataPlay {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataPlay: DataPlayRepository
  ) {}

  async execute(input: UpdateDataPlayInput): Promise<UpdateDataPlayOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dplId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;

    // Load existing entity
    const existing = await this.dataPlay.getDataPlay({ id: idValue, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${idValue}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.dataPlay.updateDataPlay({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateDataPlayOutput;
  }
}
