/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Dataplay Domain Use Cases
 * 
 * List of all use case names for the dataplay domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DATAPLAY_USE_CASES = [
  "executeCreateDataPlay",
  "executeGetDataPlay",
  "executeListDataPlays",
  "executeUpdateDataPlay"
] as const;
