/**
 * Decisions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decisions Domain Module - Composition root
 *
 * DDD: Composition root for decisions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecisionRepositoryAdapter,
} from "@asiora/adapters/decisions";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetFundingDecision,
  ExecuteListFundingDecisions,
  ExecuteRecordFundingDecision,
} from "@asiora/services/decisions/usecases";
// Ports (interfaces)
import type {
  DecisionRepository,
} from "@asiora/services/decisions/ports";

export interface DecisionsDomainModule {
  repos: {
    decisions: DecisionRepository;
  };
  useCases: {
    decisions: {
      get: ExecuteGetFundingDecision;
      list: ExecuteListFundingDecisions;
    };
  };
}

export function buildDecisionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DecisionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decisions?: DecisionRepository;
    } = {};

    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    return {
      decisions: obj.decisions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decisions: {
      get: new ExecuteGetFundingDecision(executionContext, idGenerator, repos.decisions),
      list: new ExecuteListFundingDecisions(executionContext, idGenerator, repos.decisions),
    },
  };
  return { repos, useCases: useCases as DecisionsDomainModule["useCases"] };
}
