/**
 * AllianceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AllianceRepository Port
 *
 * DDD: Application port for alliancerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAllianceScoreInput, CreateAllianceScoreOutput, GetAllianceScoreInput, GetAllianceScoreOutput, ListAllianceScoresInput, ListAllianceScoresOutput } from "../dto/alliance.dto";
export interface AllianceRepository {
  listAllianceScores(input: ListAllianceScoresInput): Promise<ListAllianceScoresOutput>;
  createAllianceScore(input: CreateAllianceScoreInput): Promise<CreateAllianceScoreOutput>;
  getAllianceScore(input: GetAllianceScoreInput): Promise<GetAllianceScoreOutput>;
}

export type { CreateAllianceScoreInput, CreateAllianceScoreOutput, GetAllianceScoreInput, GetAllianceScoreOutput, ListAllianceScoresInput, ListAllianceScoresOutput } from "../dto/alliance.dto";
