/**
 * EthicRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EthicRepository Port
 *
 * DDD: Application port for ethicrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEthicsFlagsInput, ListEthicsFlagsOutput, RaiseEthicsFlagInput, RaiseEthicsFlagOutput } from "../dto/ethic.dto";
export interface EthicRepository {
  listEthicsFlags(input: ListEthicsFlagsInput): Promise<ListEthicsFlagsOutput>;
  raiseEthicsFlag(input: RaiseEthicsFlagInput): Promise<RaiseEthicsFlagOutput>;
}

export type { ListEthicsFlagsInput, ListEthicsFlagsOutput, RaiseEthicsFlagInput, RaiseEthicsFlagOutput } from "../dto/ethic.dto";
