/**
 * WaiverRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WaiverRepository Port
 *
 * DDD: Application port for waiverrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { WaiveEthicsFlagInput, WaiveEthicsFlagOutput } from "../dto/waiver.dto";
export interface WaiverRepository {
  waiveEthicsFlag(input: WaiveEthicsFlagInput): Promise<WaiveEthicsFlagOutput>;
}

export type { WaiveEthicsFlagInput, WaiveEthicsFlagOutput } from "../dto/waiver.dto";
