/**
 * ExpireRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpireRepository Port
 *
 * DDD: Application port for expirerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExpireIdeaIntakeInput, ExpireIdeaIntakeOutput } from "../dto/expire.dto";
export interface ExpireRepository {
  expireIdeaIntake(input: ExpireIdeaIntakeInput): Promise<ExpireIdeaIntakeOutput>;
}

export type { ExpireIdeaIntakeInput, ExpireIdeaIntakeOutput } from "../dto/expire.dto";
