/**
 * IntakeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: intakes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntakeRepository Port
 *
 * DDD: Application port for intakerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateIdeaIntakeInput, CreateIdeaIntakeOutput, GetIdeaIntakeInput, GetIdeaIntakeOutput, ListIdeaIntakesInput, ListIdeaIntakesOutput } from "../dto/intake.dto";
export interface IntakeRepository {
  listIdeaIntakes(input: ListIdeaIntakesInput): Promise<ListIdeaIntakesOutput>;
  createIdeaIntake(input: CreateIdeaIntakeInput): Promise<CreateIdeaIntakeOutput>;
  getIdeaIntake(input: GetIdeaIntakeInput): Promise<GetIdeaIntakeOutput>;
}

export type { CreateIdeaIntakeInput, CreateIdeaIntakeOutput, GetIdeaIntakeInput, GetIdeaIntakeOutput, ListIdeaIntakesInput, ListIdeaIntakesOutput } from "../dto/intake.dto";
