/**
 * Scenario DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scenario DTOs
 *
 * DDD: Application DTOs for Scenario use cases.
 */

import type { GetInitiativeScenarioParams, ListScenarioPosturesParams, SetInsuranceScenarioParams, SetInsuranceScenarioRequestInput } from "@asiora/core/scenarios/types";

export type ListScenarioPosturesInput = ListScenarioPosturesParams;

export type GetInitiativeScenarioInput = GetInitiativeScenarioParams;

export type SetInsuranceScenarioInput = SetInsuranceScenarioParams & SetInsuranceScenarioRequestInput;

export type ListScenarioPosturesOutput = {};

export type GetInitiativeScenarioOutput = {};

export type SetInsuranceScenarioOutput = {};
