/**
 * Handlers for Talent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GatesDomainModule } from "../dependencies/gates-ddd.dependencies.js";
import type { EvaluateTalentGateInput, ListTalentGatesInput } from "@asiora/services/gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/gates/talent
 * Operation: listTalentGates
 */
export async function listTalentGates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], failedOnly?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTalentGatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.talents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/gates/talent
 * Operation: evaluateTalentGate
 */
export async function evaluateTalentGate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EvaluateTalentGateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.talents.create.execute(input);
  return reply.code(200).send(result);
}


