/**
 * Routes for Alliance
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAllianceScore, getAllianceScore, listAllianceScores } from "../handlers/alliance.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function allianceRoutes(fastify: FastifyInstance) {
  // POST /v1/alliances (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/alliances",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlliancesDependenciesForRequest();
        await createAllianceScore(request, reply, deps);
      });
    }
  );


  // GET /v1/alliances (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/alliances",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlliancesDependenciesForRequest();
        await listAllianceScores(request, reply, deps);
      });
    }
  );


  // GET /v1/alliances/{allianceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/alliances/:allianceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { allianceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlliancesDependenciesForRequest();
        await getAllianceScore(request, reply, deps);
      });
    }
  );


}
