/**
 * ExecuteListAllianceScores - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAllianceScores Use Case
 *
 * DDD: Application use case for list Alliance.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAllianceScoresInput, ListAllianceScoresOutput } from "../dto/alliance.dto";
import type { ExecutionContextService, IdGeneratorService } from "@asiora/services/_shared/index.js";
import type { AllianceRepository } from "../ports";

export class ExecuteListAllianceScores {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alliance: AllianceRepository
  ) {}

  async execute(input: ListAllianceScoresInput): Promise<ListAllianceScoresOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.alnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.alliance.listAllianceScores({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAllianceScoresOutput;
  }
}
