/**
 * Handlers for Overlap
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OverlapsDomainModule } from "../dependencies/overlaps-ddd.dependencies.js";
import type { CreateOverlapClusterInput, GetOverlapClusterInput, ListOverlapClustersInput } from "@asiora/services/overlaps";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/overlaps
 * Operation: listOverlapClusters
 */
export async function listOverlapClusters(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: OverlapsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListOverlapClustersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.overlaps.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/overlaps
 * Operation: createOverlapCluster
 */
export async function createOverlapCluster(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: OverlapsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateOverlapClusterInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.overlaps.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/overlaps/{overlapId}
 * Operation: getOverlapCluster
 */
export async function getOverlapCluster(
  request: FastifyRequest<{ Params: { overlapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OverlapsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOverlapClusterInput = {
    overlapId: request.params.overlapId,
  };
  const result = await deps.useCases.overlaps.get.execute(input);
  return reply.code(200).send(result);
}


