/**
 * Handlers for Resolve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlaps
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OverlapsDomainModule } from "../dependencies/overlaps-ddd.dependencies.js";
import type { ResolveOverlapClusterInput } from "@asiora/services/overlaps";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/overlaps/{overlapId}/resolve
 * Operation: resolveOverlapCluster
 */
export async function resolveOverlapCluster(
  request: FastifyRequest<{ Params: { overlapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OverlapsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ResolveOverlapClusterInput = {
    overlapId: request.params.overlapId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.resolves.get.execute(input);
  return reply.code(200).send(result);
}


