/**
 * CreateAllianceScore handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alliances
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createAllianceScore } from "@asiora/api-server/domains/alliances/handlers";
import type { AlliancesDDDDependencies } from "@asiora/api-server/domains/alliances";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { ALLIANCES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateAllianceScore", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlliancesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlliancesDDDDependencies>(
      ALLIANCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateAllianceScore, "execute").mockResolvedValue(useCaseResult);

    await createAllianceScore(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateAllianceScore.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
