/**
 * GetDataPlay handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDataPlay } from "@asiora/api-server/domains/dataplay/handlers";
import type { DataplayDDDDependencies } from "@asiora/api-server/domains/dataplay";
import { createDataPlay as createDataPlayEntity } from "@asiora/factories/dataplay";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { DATAPLAY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDataPlay", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataplayDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataplayDDDDependencies>(
      DATAPLAY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDataPlayEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDataPlay, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { dataPlayId: entity.id };

    await getDataPlay(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDataPlay.execute).toHaveBeenCalledWith(expect.objectContaining({ dataPlayId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { dataPlayId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDataPlay, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDataPlay(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
