/**
 * ListDataPlays handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dataplay
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDataPlays } from "@asiora/api-server/domains/dataplay/handlers";
import type { DataplayDDDDependencies } from "@asiora/api-server/domains/dataplay";
import { createDataPlay as createDataPlayEntity } from "@asiora/factories/dataplay";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@asiora/tests/shared";
import { DATAPLAY_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDataPlays", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataplayDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataplayDDDDependencies>(
      DATAPLAY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDataPlayEntity({ orgId }),
      createDataPlayEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDataPlays, "execute").mockResolvedValue(useCaseResult);

    await listDataPlays(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDataPlays.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
