/**
 * Initiative Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiatives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { InitiativeEntity } from "@asiora/core/initiatives/models/index.js";
import { initiativesSchemas } from "@asiora/core/initiatives";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ini";

export function createInitiative(overrides: Partial<InitiativeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ini_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "intake",
    vertical: overrides.vertical ?? "aiOps",
    ...overrides,
  };

  return initiativesSchemas.Initiative.parse(raw);
}

export function initiativeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createInitiative(overrides));
}
