/**
 * Scenarios DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scenarios
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scenarios Domain Module - Composition root
 *
 * DDD: Composition root for scenarios domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ScenarioRepositoryAdapter,
} from "@asiora/adapters/scenarios";
import { getIdGeneratorService } from "@asiora/adapters";
import type { AdapterDynamoDBClient } from "@asiora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetInitiativeScenario,
  ExecuteListScenarioPostures,
  ExecuteSetInsuranceScenario,
} from "@asiora/services/scenarios/usecases";
// Ports (interfaces)
import type {
  ScenarioRepository,
} from "@asiora/services/scenarios/ports";

export interface ScenariosDomainModule {
  repos: {
    scenarios: ScenarioRepository;
  };
  useCases: {
    scenarios: {
      get: ExecuteGetInitiativeScenario;
      list: ExecuteListScenarioPostures;
      update: ExecuteSetInsuranceScenario;
    };
  };
}

export function buildScenariosDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ScenariosDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      scenarios?: ScenarioRepository;
    } = {};

    obj.scenarios = new ScenarioRepositoryAdapter(dynamoClient);
    return {
      scenarios: obj.scenarios!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    scenarios: {
      get: new ExecuteGetInitiativeScenario(executionContext, idGenerator, repos.scenarios),
      list: new ExecuteListScenarioPostures(executionContext, idGenerator, repos.scenarios),
      update: new ExecuteSetInsuranceScenario(executionContext, idGenerator, repos.scenarios),
    },
  };
  return { repos, useCases: useCases as ScenariosDomainModule["useCases"] };
}
